name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.232.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43ba9da85eac230f16cdb748f7f4a4c78f9bcb1cc8f1cc681793960ded6abbaa"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
